### ISSUE TITLE
Dense2Csr OpenCL Run-time compilation error

### ISSUE THREAD

**Issue by kvaragan** [clMathLibraries/clSPARSE#161]
I get this error: test case: smallMTX (Dubcova1.mtx, same error for all files)
---------------------------------------
"/tmp/OCL4949T17.cl", line 40: error: unrecognized token
      #pragma OPENCL EXTENSION cl_khr_global_int32_base_atomics : require
                                                                  ^

"/tmp/OCL4949T17.cl", line 41: warning: unrecognized #pragma
      #pragma OPENCL_EXTENSION cl_khr_global_int32_extended_atomics : require
              ^

1 error detected in the compilation of "/tmp/OCL4949T17.cl".
Frontend phase failed compilation.
[Dubcova1.txt](https://github.com/clMathLibraries/clSPARSE/files/13015/Dubcova1.txt)

**Comment by kknox** [comment]
@kvaragan , try replacing 'require' with 'enable'

**Comment by jlgreathouse** [comment]
Better yet, change the `#if` statement on 41 to the following:
`#if __OPENCL_VERSION__ <= CL_VERSION_1_0 && (defined(ATOMIC_FLOAT) || defined (ATOMIC_INT))`

I used the "require" term because [the online documentation for OpenCL 1.0](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/EXTENSION.html) implied this was the correct syntax (compared to 1.1 and above, which all use "enable". The [PDF documentation for OpenCL 1.0](https://www.khronos.org/registry/cl/specs/opencl-1.0.pdf) says that "enable" is also the right term there. I'm not sure which to follow, as I don't have an OpenCL 1.0 box to test this on. I'm fine changing all of these to "enable" all over clSPARSE if we're sure this is the right syntax for OpenCL 1.0 distributions.

In any case, OpenCL versions > 1.0 do not require the 32-bit atomic extensions, because 32-bit atomics were promoted to core features. You're seeing this error because I forgot to check the OpenCL version for this file. See the top of csrmv_adaptive.cl for an example where this check is done correctly.

**Comment by jlgreathouse** [comment]
I see that "require" is [a bug in the OpenCL documentation](https://www.khronos.org/bugzilla/show_bug.cgi?id=345) that they (perhaps) have no intention of fixing.  I will shortly submit a patch that fixes this.
